export const products = [
  {
    id: 1,
    title: "Camiseta de Algodón",
    price: 19.99,
    description: "Camiseta cómoda y transpirable de algodón.",
    img: "https://res.cloudinary.com/dxe1ly9oz/image/upload/v1706582123/samples/smile.jpg",
    stock: 50,
    categories: ["hombres", "Camisetas", "Algodón"],
  },
  {
    id: 2,
    title: "Jeans Ajustados",
    price: 39.99,
    description: "Jeans ajustados de alta calidad para un look moderno.",
    img: "https://res.cloudinary.com/dxe1ly9oz/image/upload/v1709167313/c618238ff9b0332ba89b2702d6bea8f3_nies7x.jpg",
    stock: 30,
    categories: ["mujeres", "Jeans", "Ajustados"],
  },
  {
    id: 3,
    title: "Chaqueta de Cuero",
    price: 89.99,
    description: "Chaqueta elegante de cuero genuino.",
    img: "https://res.cloudinary.com/dxe1ly9oz/image/upload/c_thumb,w_200,g_face/v1706582123/samples/smile.jpg",
    stock: 20,
    categories: ["kids", "Chaquetas", "Cuero"],
  },
  {
    id: 4,
    title: "Vestido Floral",
    price: 49.99,
    description: "Vestido elegante con estampado floral.",
    img: "https://res.cloudinary.com/dxe1ly9oz/image/upload/v1709167313/c618238ff9b0332ba89b2702d6bea8f3_nies7x.jpg",
    stock: 25,
    categories: ["mujeres", "Vestidos", "Floral"],
  },
  {
    id: 5,
    title: "Sudadera con Capucha",
    price: 29.99,
    description: "Sudadera cómoda con capucha y bolsillo frontal.",
    img: "https://res.cloudinary.com/dxe1ly9oz/image/upload/c_thumb,w_200,g_face/v1706582123/samples/smile.jpg",
    stock: 40,
    categories: ["kids", "Sudaderas", "Casual"],
  },
  {
    id: 6,
    title: "Falda Plisada",
    price: 34.99,
    description: "Falda plisada de estilo retro.",
    img: "https://res.cloudinary.com/dxe1ly9oz/image/upload/v1709167313/c618238ff9b0332ba89b2702d6bea8f3_nies7x.jpg",
    stock: 15,
    categories: ["mujeres", "Faldas", "Plisadas"],
  },
  {
    id: 7,
    title: "Camisa a Cuadros",
    price: 24.99,
    description: "Camisa casual a cuadros para un look relajado.",
    img: "https://res.cloudinary.com/dxe1ly9oz/image/upload/c_thumb,w_200,g_face/v1706582123/samples/smile.jpg",
    stock: 35,
    categories: ["hombres", "Camisas", "Cuadros"],
  },
  {
    id: 8,
    title: "Zapatillas Deportivas",
    price: 59.99,
    description: "Zapatillas deportivas modernas y cómodas.",
    img: "https://res.cloudinary.com/dxe1ly9oz/image/upload/v1709167313/c618238ff9b0332ba89b2702d6bea8f3_nies7x.jpg",
    stock: 22,
    categories: ["mujeres", "Zapatillas", "Deportivas"],
  },
];
